SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping constraints from [dbo].[Personitas]'
GO
ALTER TABLE [dbo].[Personitas] DROP CONSTRAINT [PK__Personit__54B45CCD8ED1A7EA]
GO
PRINT N'Dropping [dbo].[Personitas]'
GO
DROP TABLE [dbo].[Personitas]
GO

